###服务端口号
server:
  #port: 8100 注册中心1的端口
  port: 8200  #注册中心2的端口
spring:
  application:
    name: eurekaServer
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:8200/eureka/   注册中心1需要连接的注册中心
      defaultZone: http://127.0.0.1:8100/eureka/   #注册中心2需要连接的注册中心
    ###多注册中心需要配置为true
    register-with-eureka: true
    ###多注册中心需要配置为true
    fetch-registry: true
