###会员项目的端口号
server:
  port: 8001
###注意此处一定要给对应的服务起一个别名----通过将对应的别名注册到注册中心中
spring:
  application:
    name: memberServer
eureka:
  client:
    service-url:
      ##### 当前会员服务注册到eureka服务地址 此处使用了多个注册中心的配置操作处理
      defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true